### PR TITLE
Added: Copy to clipboard feature

### PR DESCRIPTION
**Pull request by rabingaire**
#2

### CODE REVIEW

**Comment by danilowoz** [comment]
Really great work @rabingaire!

I just would like that you update the styles (design things 😜)

```diff
.copy-to-clipboard {
   float: right;
   margin-top: -40px;
   color: #fff;
   cursor: pointer;
-  display: none;
-  margin-top: -40px;
+  opacity: 0;
+  transition: opacity .2s ease;
+  text-transform: uppercase;
+  font-size: 0.6em;
+  color: #999;
+  letter-spacing: 2px;
+  margin-top: -35px;

}

.app-editor:hover .copy-to-clipboard {
-  display: inline;
+  opacity: 1;
}

+.copy-to-clipboard:active {
+  transform: translateY(1px)
+}
```

Just one more thing, what do you think to add the `import` on the clipboard as well? 
I think it makes sense

Thanks again dude

**Comment by rabingaire** [comment]
Hey, thanks for the comment, I have updated the code as per your CSS, I am not a designer so I miss these things LOL. Anyway adding import can be added, let me work on that as well 👍

**Comment by rabingaire** [comment]
Hey @danilowoz I have added import to the code that is copied to the clipboard 👍

**Comment by danilowoz** [comment]
Great! 🎉

**Pull request merged**
